#!/bin/bash

# This is the input for pseudo_analysis script. It will generate the electron density .log file for visualization.

# DO NOT LEAVE ANY FREE SPACE AFTER THE ARGUMENT. REMEMBER TO LEAVE THE SPACES BETWEEN =

# .log from GAMESS-SMC
LOG = res-bhs2.log

# CSF's construction type 
CSF    = SE

# Pseudo-spectrum generation (hcomp)
SQUARE = NO
PRTVEC = YES
PRNTOL = -1.0
JOBTYP = SEL
ELOWER =  -5.0
EUPPER = 20.0

# SE CSF's pseudo-eigenstates configuration
MIN_ENERG =-3.0
MAX_ENERG = 10
THRESHOLD = 0.3

# Plot pseudo-states electron density (YES; NO )
PLOT = YES